In [3]:
!pip install pingouin

Requirement already satisfied: pingouin in /Users/fionazhu/opt/anaconda3/lib/python3.8/site-packages (0.5.0)
Requirement already satisfied: statsmodels>=0.12.0 in /Users/fionazhu/opt/anaconda3/lib/python3.8/site-packages (from pingouin) (0.12.2)
Requirement already satisfied: matplotlib>=3.0.2 in /Users/fionazhu/opt/anaconda3/lib/python3.8/site-packages (from pingouin) (3.3.4)
Requirement already satisfied: pandas>=1.0 in /Users/fionazhu/opt/anaconda3/lib/python3.8/site-packages (from pingouin) (1.2.4)
Requirement already satisfied: seaborn>=0.9.0 in /Users/fionazhu/opt/anaconda3/lib/python3.8/site-packages (from pingouin) (0.11.1)
Requirement already satisfied: numpy>=1.19 in /Users/fionazhu/opt/anaconda3/lib/python3.8/site-packages (from pingouin) (1.20.1)
Requirement already satisfied: pandas-flavor>=0.2.0 in /Users/fionazhu/opt/anaconda3/lib/python3.8/site-packages (from pingouin) (0.2.0)
Requirement already satisfied: outdated in /Users/fionazhu/opt/anaconda3/lib/python3.8/site-packages (from pingouin) (0.2.1)
Requirement already satisfied: tabulate in /Users/fionazhu/opt/anaconda3/lib/python3.8/site-packages (from pingouin) (0.8.9)
Requirement already satisfied: scikit-learn in /Users/fionazhu/opt/anaconda3/lib/python3.8/site-packages (from pingouin) (0.24.1)
Requirement already satisfied: scipy>=1.7 in /Users/fionazhu/opt/anaconda3/lib/python3.8/site-packages (from pingouin) (1.7.2)
Requirement already satisfied: python-dateutil>=2.1 in /Users/fionazhu/opt/anaconda3/lib/python3.8/site-packages (from matplotlib>=3.0.2->pingouin) (2.8.1)
Requirement already satisfied: kiwisolver>=1.0.1 in /Users/fionazhu/opt/anaconda3/lib/python3.8/site-packages (from matplotlib>=3.0.2->pingouin) (1.3.1)
Requirement already satisfied: cycler>=0.10 in /Users/fionazhu/opt/anaconda3/lib/python3.8/site-packages (from matplotlib>=3.0.2->pingouin) (0.10.0)
Requirement already satisfied: pillow>=6.2.0 in /Users/fionazhu/opt/anaconda3/lib/python3.8/site-packages (from matplotlib>=3.0.2->pingouin) (8.2.0)
Requirement already satisfied: pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.3 in /Users/fionazhu/opt/anaconda3/lib/python3.8/site-packages (from matplotlib>=3.0.2->pingouin) (2.4.7)
Requirement already satisfied: six in /Users/fionazhu/opt/anaconda3/lib/python3.8/site-packages (from cycler>=0.10->matplotlib>=3.0.2->pingouin) (1.15.0)
Requirement already satisfied: pytz>=2017.3 in /Users/fionazhu/opt/anaconda3/lib/python3.8/site-packages (from pandas>=1.0->pingouin) (2021.1)
Requirement already satisfied: xarray in /Users/fionazhu/opt/anaconda3/lib/python3.8/site-packages (from pandas-flavor>=0.2.0->pingouin) (0.19.0)
Requirement already satisfied: patsy>=0.5 in /Users/fionazhu/opt/anaconda3/lib/python3.8/site-packages (from statsmodels>=0.12.0->pingouin) (0.5.1)
Requirement already satisfied: requests in /Users/fionazhu/opt/anaconda3/lib/python3.8/site-packages (from outdated->pingouin) (2.25.1)
Requirement already satisfied: littleutils in /Users/fionazhu/opt/anaconda3/lib/python3.8/site-packages (from outdated->pingouin) (0.2.2)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /Users/fionazhu/opt/anaconda3/lib/python3.8/site-packages (from requests->outdated->pingouin) (1.26.4)
Requirement already satisfied: certifi>=2017.4.17 in /Users/fionazhu/opt/anaconda3/lib/python3.8/site-packages (from requests->outdated->pingouin) (2020.12.5)
Requirement already satisfied: idna<3,>=2.5 in /Users/fionazhu/opt/anaconda3/lib/python3.8/site-packages (from requests->outdated->pingouin) (2.10)
Requirement already satisfied: chardet<5,>=3.0.2 in /Users/fionazhu/opt/anaconda3/lib/python3.8/site-packages (from requests->outdated->pingouin) (4.0.0)
Requirement already satisfied: threadpoolctl>=2.0.0 in /Users/fionazhu/opt/anaconda3/lib/python3.8/site-packages (from scikit-learn->pingouin) (2.1.0)
Requirement already satisfied: joblib>=0.11 in /Users/fionazhu/opt/anaconda3/lib/python3.8/site-packages (from scikit-learn->pingouin) (1.0.1)
Requirement already satisfied: setuptools>=40.4 in /Users/fionazhu/opt/anaconda3/lib/python3.8/site-packages (from xarray->pandas-flavor>=0.2.0->pingouin) (52.0.0.post20210125)

In [5]:
# these packages are often used in data analyses, so import them first. 
%matplotlib inline

# pandas for data process, seaborn for plotting, in addition, matplotlib
import numpy as np
import pandas as pd  # manage data
import seaborn as sns # statistical data visualization
import matplotlib.pyplot as plt
import pingouin as pg

## Repeated measures ANOVA of the mean correct rates with Experiment (1-4)

In [9]:
#A repeated measures ANOVA of the mean correct rates with Experiment (1-4) 
dat = pd.read_csv('modelrlt/models/log_rstan/rlt/WMCrr.csv')
dat.head()

   Unnamed: 0   Exp WMSize  NSub   m_WMCrr    n  se_WMCrr
0           1  Exp1    low     1  0.916667  120  0.025442
1           2  Exp1    low     2  0.925000  120  0.024246
2           3  Exp1    low     3  0.883333  120  0.029551
3           4  Exp1    low     4  0.866667  120  0.031292
4           5  Exp1    low     5  0.958333  120  0.018395

In [34]:
Crr_exp = dat.groupby('Exp').m_WMCrr.mean().round(2)
Crr_exp

Exp
Exp1    0.81
Exp2    0.76
Exp3    0.73
Exp4    0.70
Name: m_WMCrr, dtype: float64

In [39]:
pg.pairwise_ttests(data = dat, 
            dv = 'm_WMCrr',  within = 'Exp', subject = 'NSub', padjust = 'holm')

,Contrast,A,B,Paired,Parametric,T,dof,alternative,p-unc,p-corr,p-adjust,BF10,hedges
0,Exp,Exp1,Exp2,True,True,2.132026,15.0,two-sided,0.049946,0.149837,holm,1.504,0.814075
1,Exp,Exp1,Exp3,True,True,5.867934,15.0,two-sided,0.000031,0.000186,holm,807.098,1.585307
2,Exp,Exp1,Exp4,True,True,5.638092,15.0,two-sided,0.000047,0.000236,holm,554.231,1.882971
3,Exp,Exp2,Exp3,True,True,2.121656,15.0,two-sided,0.050934,0.149837,holm,1.482,0.605428
4,Exp,Exp2,Exp4,True,True,4.882416,15.0,two-sided,0.000199,0.000796,holm,155.652,0.986116
5,Exp,Exp3,Exp4,True,True,1.703510,15.0,two-sided,0.109095,0.149837,holm,0.835,0.474697

LSD comparison showed significantly higher correct rates in Experiment 1 (mean of .81) than that in Experiments 2-4 (mean of .76, .73 and .70 respectively, all _ps < .025_)

In [16]:
dat.groupby('WMSize').m_WMCrr.mean()

WMSize
high      0.648307
low       0.874349
medium    0.725911
Name: m_WMCrr, dtype: float64

In [27]:
dat_new = dat.groupby(['WMSize','NSub']).agg({'m_WMCrr':'mean'})
dat_new.head()

              m_WMCrr
WMSize NSub
high   1     0.677083
       2     0.568750
       3     0.606250
       4     0.604167
       5     0.695833

In [41]:
pg.rm_anova(data = dat, 
            dv = 'm_WMCrr', 
            within = ['Exp','WMSize'], 
            subject = 'NSub', detailed = True)

/Users/fionazhu/opt/anaconda3/lib/python3.8/site-packages/pingouin/distribution.py:459: UserWarning: Epsilon values might be innaccurate in two-way repeated measures design where each  factor has more than 2 levels. Please  double-check your results.
  warnings.warn("Epsilon values might be innaccurate in "

,Source,SS,ddof1,ddof2,MS,F,p-unc,p-GG-corr,np2,eps
0,Exp,0.330837,3,45,0.110279,15.260634,5.471974e-07,1.672614e-05,0.504306,0.706830
1,WMSize,1.688553,2,30,0.844277,439.695600,5.964274e-23,1.260730e-21,0.967011,0.936301
2,Exp * WMSize,0.022749,6,90,0.003791,2.062507,6.544630e-02,1.446444e-01,0.120879,0.334172

In [42]:
# post-hoc pair-wise tests
# use the same inputs as rm_anova(), and specify padjust: 'bonf', 'holm', 'fdr_bh' etc.
pg.pairwise_ttests(data = dat.query('Exp == "Exp1"'), 
            dv = 'm_WMCrr',  within = 'WMSize', subject = 'NSub', padjust = 'holm')

,Contrast,A,B,Paired,Parametric,T,dof,alternative,p-unc,p-corr,p-adjust,BF10,hedges
0,WMSize,high,low,True,True,-13.603306,15.0,two-sided,7.650379e-10,2.295114e-09,holm,1.263e+07,-3.320000
1,WMSize,high,medium,True,True,-8.177989,15.0,two-sided,6.559945e-07,6.559945e-07,holm,2.586e+04,-1.296554
2,WMSize,low,medium,True,True,12.541506,15.0,two-sided,2.359283e-09,4.718566e-09,holm,4.471e+06,2.481272

## A repeated measures ANOVA of weight of prior with Experiment (1-4)